import { type Metadata } from "next";

// ** Clerk Authentication
import { ClerkProvider } from "@clerk/nextjs";

// ** Fonts
import { Geist, Geist_Mono } from "next/font/google";

// ** Global Styles
import "@/styles/globals.css";

// ** Components
import Header from "@/components/Header";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <Header />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}