#:schema node_modules/wrangler/config-schema.json

name = "community-forums-server"
main = "src/index.ts"
compatibility_date = "2025-01-08"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[observability]
enabled = true

[env.production]
name = "community-forums-server"

[env.production.vars]
NODE_ENV = "production"
NODE_VERSION="20.0.0" # Define the Node version to avoid build errors.
CLERK_SECRET_KEY="xxxxxxxxxxxxxxxxxxx"
CLERK_PUBLISHABLE_KEY = "xxxxxxxxxxxxxxxxxxx"
SIGNING_SECRET="xxxxxxxxxxxxxxxxxxx"
DATABASE_URL = "xxxxxxxxxxxxxxxxxxx"
ALLOWED_ORIGIN = "https://forums-x.vercel.app,http://localhost:3000"

[env.development]
name = "community-forums-server-dev"

[env.development.vars]
NODE_ENV = "development"
NODE_VERSION="20.0.0"
CLERK_SECRET_KEY="xxxxxxxxxxxxxxxxxxx"
CLERK_PUBLISHABLE_KEY = "xxxxxxxxxxxxxxxxxxx"
SIGNING_SECRET="xxxxxxxxxxxxxxxxxxx"
DATABASE_URL = "xxxxxxxxxxxxxxxxxxx"
ALLOWED_ORIGIN = "https://forums-x.vercel.app,http://localhost:3000"