#:schema node_modules/wrangler/config-schema.json

name = "server"
main = "src/index.ts"
compatibility_date = "2025-01-08"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[vars]
NODE_VERSION="20.0.0" # Define the Node version to avoid build errors.
# route = "server.xxxxxxxx.com/*" # Assign your worker to this domain
database_url = "xxxxxxx"

[vars.production]
NODE_ENV = "production"
CLERK_SECRET_KEY = "xxxxxxxx"
CLERK_PUBLISHABLE_KEY = "xxxxxxxxxxxx"

[vars.development]
NODE_ENV = "development"
CLERK_SECRET_KEY = "xxxxxxxxxxxx"
CLERK_PUBLISHABLE_KEY = "xxxxxxxxxxxx"